#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

runApplication ideasUnvToFoam Spacer_4x6.unv

runApplication transformPoints -scale '(0.001 0.001 0.001)' # convert mesh units from mm to m

#runApplication funkySetFields -time 0

runApplication makeFaMesh

runApplication decomposePar

runParallel silicaROicoFoam

runApplication reconstructPar

#------------------------------------------------------------------------------
